export const ADD_STORY = 'ADD_STORY'
export const SET_STORY = 'SET_STORY'
export const VIEW_STORY = 'VIEW_STORY'
export const SET_GUEST_NAME = 'SET_GUEST_NAME'

export const INCREASE_TIMER_MINUTES = 'INCREASE_TIMER_MINUTES'
export const DECREASE_TIMER_MINUTES = 'DECREASE_TIMER_MINUTES'

export const INCREASE_TIMER_SECONDS = 'INCREASE_TIMER_SECONDS'
export const DECREASE_TIMER_SECONDS = 'DECREASE_TIMER_SECONDS'

export const SET_SHOW_MODAL = 'SET_SHOW_MODAL'
export const START_VOTING = 'START_VOTING'
export const STOP_VOTING = 'STOP_VOTING'
export const RESET_VOTING = 'RESET_VOTING'
export const HIDE_SHOW_VOTES = 'HIDE_SHOW_VOTES'

export const ADD_PLAYER = 'ADD_PLAYER'
export const UPDATE_PLAYERS = 'UPDATE_PLAYERS'

export const SET_VOTES = 'SET_VOTES'